hotel/urls.py
from django.urls import path
from .views import create_hotel, read_hotel, update_hotel

app_name = 'hotel'

urlpatterns = [
    path('create/', create_hotel, name='create'),
    path('read/', read_hotel, name='read'),
    path('update/', update_hotel, name='update'),
]

ruangan_hotel/urls.py
from django.urls import path
from .views import create_ruangan_hotel, post_kode_ruangan, read_ruangan_hotel,update_ruangan_hotel, delete_ruangan_hotel

app_name = 'ruangan_hotel'

urlpatterns = [
    path('create/', create_ruangan_hotel, name='create'),
    path('post/', post_kode_ruangan, name = "post_kode_ruangan"),
    path('read/', read_ruangan_hotel, name='read'),
    path('update/', update_ruangan_hotel, name='update'),
    path('delete/', delete_ruangan_hotel, name='delete'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('jadwal-faskes/', include('jadwal_faskes.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('reservasiRS/', include('reservasiRS.urls')),
    path('transaksiRS/', include('transaksirs.urls')),
    path('jadwaldokter/',include('jadwaldokter.urls')),

    path('hotel/', include('hotel.urls')),
    path('paketmakan/', include('paketmakan.urls')),
    path('ruangan_hotel/', include('ruangan_hotel.urls')),
    path('reservasi_hotel/', include('Reservasi_Hotel.urls')),
    path('transaksi_hotel/', include('transaksi_hotel.urls')),
    path('transaksi_booking/', include('transaksi_booking.urls')),
]

ruangan_hotel/models.py
from django.db import models

# Create your models here.

ruangan_hotel/forms.py
from django import forms
from django.db import connection

class Create_Ruangan_Hotel_Form(forms.Form):
    kode_hotel_list = []
    kode_hotel = forms.ChoiceField(choices=kode_hotel_list, required=True)
    kode_ruangan = forms.CharField(label=("Kode Ruangan"), required=True, max_length=5)
    jenis_bed = forms.CharField(label=("Jenis Bed"), required=True, max_length=10)
    tipe = forms.CharField(label=("Tipe"), required=True, max_length=10)
    harga_per_hari = forms.IntegerField(label=("Harga per Hari"), required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['kode_hotel'].widget.attrs['id'] = 'kodehotel'
        self.fields['jenis_bed'].widget.attrs['id'] = 'jenisbed'
        self.fields['tipe'].widget.attrs['id'] = 'tipe'
        self.fields['harga_per_hari'].widget.attrs['id'] = 'harga'
        self.fields['kode_ruangan'].widget.attrs['readonly'] = True
        self.fields['kode_ruangan'].widget.attrs['class'] = 'disabled'
        self.fields['kode_ruangan'].widget.attrs['id'] = 'koderuangan'

        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT KODE,KODE FROM SIRUCO.HOTEL;")
            self.fields['kode_hotel'].choices = cursor.fetchall()

class Update_Ruangan_Hotel_Form(forms.Form):
    kode_hotel = forms.CharField(label=("Kode Hotel"), required=True)
    kode_ruangan = forms.CharField(label=("Kode Ruangan"), required=True, max_length=5)
    jenis_bed = forms.CharField(label=("Jenis Bed"), required=True, max_length=10)
    tipe = forms.CharField(label=("Tipe"), required=True, max_length=10)
    harga_per_hari = forms.IntegerField(label=("Harga per Hari"), required=True)

    def __init__(self, *args, **kwargs):
        super(Update_Ruangan_Hotel_Form, self).__init__(*args, **kwargs)
        self.fields['kode_hotel'].widget.attrs['readonly'] = True
        self.fields['kode_hotel'].widget.attrs['class'] = 'disabled'
        self.fields['kode_hotel'].widget.attrs['id'] = 'kode_hotel'
        self.fields['kode_ruangan'].widget.attrs['readonly'] = True
        self.fields['kode_ruangan'].widget.attrs['class'] = 'disabled'
        self.fields['kode_ruangan'].widget.attrs['id'] = 'kode_ruangan'

ruangan_hotel/views.py
from datetime import datetime
from django.db import connection
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .forms import *

def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        if 'is_login' not in request.session:
            return redirect('login:login_or_register')
        else:
            return function(request, *args, **kwargs)
    return wrapper

@ user_login_required
def create_ruangan_hotel(request):
    if request.session['peran'] != 'Admin Sistem':
        return redirect('login:login_or_register')
    print(request.session['username'])
    form = Create_Ruangan_Hotel_Form()
    if request.method == "POST":
        kode_hotel = request.POST['kode_hotel']
        kode_ruangan = request.POST['kode_ruangan']
        jenis_bed = request.POST['jenis_bed']
        tipe = request.POST['tipe']
        harga_per_hari = request.POST['harga_per_hari']
        data_baru = [kode_hotel, kode_ruangan, jenis_bed, tipe, harga_per_hari]
        print(data_baru)
        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO SIRUCO.HOTEL_ROOM VALUES (%s, %s, %s, %s, %s)', data_baru)
        return redirect('ruangan_hotel:read')
    return render(request, 'ruangan_hotel/create_ruangan_hotel.html', {'form': form, 'peran': request.session['peran']})

@csrf_exempt
def post_kode_ruangan(request):
    kode_hotel = request.GET.get('kode_hotel')
    print(kode_hotel)
    kode_ruangan = ''

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT KODEROOM FROM SIRUCO.HOTEL_ROOM WHERE KODEHOTEL = %s ORDER BY KODEROOM DESC LIMIT 1;", [kode_hotel])
        data = cursor.fetchall()
        # print(data)
        if (data != []):
            databaru = data[0][0][2:]
            # print(databaru)
            kode_ruangan = "RH" + manip(databaru)
            print(kode_ruangan)
        else:
            kode_ruangan = "RH001"
    return JsonResponse({'kode_ruangan': kode_ruangan})


def manip(kode):
    res = ''
    nilai = int(kode)
    print(nilai)
    nilai += 1
    res += str(nilai).zfill(3)
    print(res, "WAWAUIHAW")
    return res

@user_login_required
def read_ruangan_hotel(request):
    if request.session['peran'] != 'Pengguna Publik' and request.session['peran'] != 'Admin Satgas' and request.session['peran'] != 'Admin Sistem':
        return redirect('login:login_or_register')
    else:
        tgl = datetime.today().strftime('%Y-%m-%d')
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.HOTEL_ROOM")
            dataquery = dictfetchall(cursor)
            cursor.execute("SELECT * FROM SIRUCO.HOTEL_ROOM AS H WHERE H.koderoom NOT IN (SELECT RH.koderoom FROM SIRUCO.RESERVASI_HOTEL AS RH WHERE H.kodehotel = RH.kodehotel AND RH.tglkeluar > %s)", [tgl])
            ruangankosong = dictfetchall(cursor)
            # cursor.execute("SELECT * FROM SIRUCO.HOTEL_ROOM AS H WHERE H.koderoom IN (SELECT RH.koderoom FROM SIRUCO.RESERVASI_HOTEL AS RH WHERE RH.tglkeluar < %s)", [tgl])
            # ruangankosong2 = dictfetchall(cursor)
            # print(ruangankosong2)
            context = {'data': dataquery, 'ruangankosong':ruangankosong}
    return render(request, 'ruangan_hotel/read_ruangan_hotel.html', context)

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

@ user_login_required
def update_ruangan_hotel(request):
    if request.session['peran'] != 'Admin Sistem':
        return redirect('login:login_or_register')
    form = Update_Ruangan_Hotel_Form()
    if request.method == 'GET':
        print(request.GET.get('kode_hotel'), request.GET.get('kode_ruangan'))
        if request.GET.get('kode_hotel') is not None and request.GET.get('kode_ruangan') is not None:
            kode_hotel = request.GET.get('kode_hotel')
            kode_ruangan = request.GET.get('kode_ruangan')
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT * FROM SIRUCO.HOTEL_ROOM where kodehotel = %s AND koderoom = %s LIMIT 1;', [kode_hotel, kode_ruangan])
                data = dictfetchall(cursor)
                print("datanya")
                print(data)
            data_ruangan = {}
            data_ruangan['kode_hotel'] = data[0]['kodehotel']
            data_ruangan['kode_ruangan'] = data[0]['koderoom']
            data_ruangan['jenis_bed'] = data[0]['jenisbed']
            data_ruangan['tipe'] = data[0]['tipe']
            data_ruangan['harga_per_hari'] = data[0]['harga']
            form = Update_Ruangan_Hotel_Form(initial=data_ruangan)
    else:
        kode_hotel = request.POST['kode_hotel']
        kode_ruangan = request.POST['kode_ruangan']
        jenis_bed = request.POST['jenis_bed']
        tipe = request.POST['tipe']
        harga_per_hari = request.POST['harga_per_hari']
        data_to_update = [jenis_bed, tipe, harga_per_hari, kode_hotel, kode_ruangan]
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE SIRUCO.HOTEL_ROOM SET jenisbed = %s, tipe = %s, harga = %s WHERE kodehotel = %s and koderoom = %s", data_to_update)
        return redirect('ruangan_hotel:read')
    return render(request, 'ruangan_hotel/update_ruangan_hotel.html', {'form': form})

@user_login_required
def delete_ruangan_hotel(request):
    if request.session['peran'] != 'Admin Sistem':
        return redirect('login:login_or_register')
    if request.method == 'GET':
        if request.GET.get('kode_hotel') is not None and request.GET.get('kode_ruangan') is not None:
            kode_hotel = request.GET.get('kode_hotel')
            kode_ruangan = request.GET.get('kode_ruangan')
            with connection.cursor() as cursor:
                cursor.execute(
                    'DELETE FROM SIRUCO.HOTEL_ROOM WHERE kodehotel = %s AND koderoom = %s', [kode_hotel, kode_ruangan])
    return HttpResponseRedirect(reverse('ruangan_hotel:read'))

ruangan_hotel/templates/ruangan_hotel/create_ruangan_hotel.html
{% extends "login/landing_page.html" %}
{% block tambahStyle %}
<style>
    .disabled {
        background-color: rgba(239, 239, 239, 0.3), rgba(59, 59, 59, 0.3);
        border-color: rgba(118, 118, 118, 0.3);
    }
</style>
{% endblock tambahStyle %}
{% block content %}

<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Create Ruangan Hotel Form</h1>
        <div style="height: 20px;"></div>
        <form id="formnya" action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        console.log("HELLWOO");

        $.ajax({
            type: 'GET',
            url: "{% url 'ruangan_hotel:post_kode_ruangan' %}",
            data: {
                kode_hotel: $('#kodehotel').val()
            },
            async: false,
            success: function (response) {
                $('#koderuangan').val(response.kode_ruangan)
            }
        });

        $('#kodehotel').change(function(){
            $.ajax({
                type: 'GET',
                url: "{% url 'ruangan_hotel:post_kode_ruangan' %}",
                data: {
                    kode_hotel: $('#kodehotel').val()
                },
                async: false,
                error: function (response) {
                    console.log("yah:<");
                },
                success: function (response) {
                    console.log("SUKSES");
                        $("#koderuangan").val(response.kode_ruangan);
                }
            });
        });
    });
    </script>
{% endblock content %}

ruangan_hotel/templates/ruangan_hotel/read_ruangan_hotel.html
{% extends "login/landing_page.html" %}

{% block content %}



<h1 class="text-center">Daftar Ruangan Hotel</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Kode Hotel</th>
            <th scope="col">Kode Ruangan</th>
            <th scope="col">Jenis Bed</th>
            <th scope="col">Tipe</th>
            <th scope="col">Harga</th>

            {% if request.session.peran == 'Admin Sistem' %}
            <th scope="col"></th>
            <th scope="col"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>

        {% for content in data %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{ content.kodehotel }}</td>
            <td>{{ content.koderoom }} </td>
            <td>{{ content.jenisbed }}</td>
            <td>{{ content.tipe }}</td>
            <td>Rp{{ content.harga }}</td>

            {% if request.session.peran == 'Admin Sistem' %}
            <td>
                <form action="{% url 'ruangan_hotel:update' %}" method="get">
                    <input type="hidden" id="kode_hotel" name="kode_hotel" value="{{ content.kodehotel }}">
                    <input type="hidden" id="kode_ruangan" name="kode_ruangan" value="{{ content.koderoom }}">
                    <button type="submit" class="btn btn-outline-warning">Update</button>
                </form>
            </td>
            {% if content in ruangankosong %}
            <td>
                <form action="{% url 'ruangan_hotel:delete' %}" method="get">
                    <input type="hidden" id="kode_hotel" name="kode_hotel" value="{{ content.kodehotel }}">
                    <input type="hidden" id="kode_ruangan" name="kode_ruangan" value="{{ content.koderoom }}">
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </form>
            </td>
            {% endif %}
            {% endif %}
        </tr>

        {% endfor %}

    </tbody>
</table>


{% endblock content %}

ruangan_hotel/templates/ruangan_hotel/update_ruangan_hotel.html
{% extends "login/landing_page.html" %}
{% block tambahStyle %}
<style>
    .disabled {
        background-color: rgba(239, 239, 239, 0.3), rgba(59, 59, 59, 0.3);
        border-color: rgba(118, 118, 118, 0.3);
    }
</style>
{% endblock tambahStyle %}
{% block content %}

<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Update Ruangan Hotel Form</h1>
        <div style="height: 20px;"></div>
        <form id="formnya" action="{% url 'ruangan_hotel:update' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#formCreate').on('submit', function (e) {
            const kode_hotel = $('#kode_hotel').val();
            const kode_ruangan = $('#kode_ruangan').val();
            console.log(kode_hotel)
            console.log(kode_ruangan)
        })
    })
    </script>
{% endblock content %}