Reservasi_Hotel/urls.py
from django.urls import path
from .views import change_ruangan_hotel, create_reservasi_hotel, read_reservasi_hotel, update_reservasi_hotel, delete_reservasi_hotel
app_name = "Reservasi_Hotel"

urlpatterns = [
    path('create/', create_reservasi_hotel, name='create'),
    path('read/', read_reservasi_hotel, name='read'),
    path('ajax/', change_ruangan_hotel, name='change_ruangan_hotel'),
    path('update/', update_reservasi_hotel, name='update'),
    path('delete/', delete_reservasi_hotel, name='delete'),
]

hotel/urls.py
from django.urls import path
from .views import create_hotel, read_hotel, update_hotel

app_name = 'hotel'

urlpatterns = [
    path('create/', create_hotel, name='create'),
    path('read/', read_hotel, name='read'),
    path('update/', update_hotel, name='update'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('jadwal-faskes/', include('jadwal_faskes.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('reservasiRS/', include('reservasiRS.urls')),
    path('transaksiRS/', include('transaksirs.urls')),
    path('jadwaldokter/',include('jadwaldokter.urls')),

    path('hotel/', include('hotel.urls')),
    path('paketmakan/', include('paketmakan.urls')),
    path('ruangan_hotel/', include('ruangan_hotel.urls')),
    path('reservasi_hotel/', include('Reservasi_Hotel.urls')),
    path('transaksi_hotel/', include('transaksi_hotel.urls')),
    path('transaksi_booking/', include('transaksi_booking.urls')),
]

Reservasi_Hotel/models.py
from django.db import models

# Create your models here.

Reservasi_Hotel/forms.py
from django import forms
from django.db import connection
from django.http import request

class Create_Reservasi_Hotel(forms.Form):
    nik_list = []
    nik = forms.ChoiceField(choices=nik_list, required=True)
    tanggal_masuk = forms.DateField(label=(
        "Tanggal Masuk"), required=True, widget=forms.DateInput(attrs={'type': 'date', 'id': 'tanggal_masuk'}))
    tanggal_keluar = forms.DateField(label=(
        "Tanggal Keluar"), required=True, widget=forms.DateInput(attrs={'type': 'date', 'id': 'tanggal_keluar'}))
    kode_hotel_list = []
    kode_hotel = forms.ChoiceField(
        label=('Kode Hotel'), choices=kode_hotel_list, required=True, widget=forms.Select(attrs={'id': 'kode_hotel'}))

    def __init__(self, user, peran, *args, **kwargs):
        super(Create_Reservasi_Hotel, self).__init__(*args, **kwargs)
        self.user = user
        print("Usernameku,", self.user)
        with connection.cursor() as cursor:
            if peran == 'Admin Satgas':
                cursor.execute("SELECT NIK,NIK FROM SIRUCO.PASIEN")
                self.fields['nik'].choices = cursor.fetchall()
            else:
                cursor.execute("SELECT NIK,NIK FROM SIRUCO.PASIEN WHERE IDPENDAFTAR = %s", [self.user])
                self.fields['nik'].choices = cursor.fetchall()
            cursor.execute(
                "SELECT kode,kode FROM SIRUCO.hotel ORDER BY kode ASC")
            self.fields['kode_hotel'].choices = cursor.fetchall()
            pilih = self.fields['kode_hotel'].choices[0][0]

class Update_Reservasi_Hotel(forms.Form):
    nik = forms.CharField(
        label=("NIK Pasien"), required=True, max_length=3)
    tanggal_masuk = forms.DateField(label=(
        "Tanggal Masuk"), required=True, widget=forms.DateInput(attrs={'type': 'date', 'id': 'tanggal_masuk'}))
    tanggal_keluar = forms.DateField(label=(
        "Tanggal Keluar"), required=True, widget=forms.DateInput(attrs={'type': 'date', 'id': 'tanggal_keluar'}))
    kode_hotel = forms.CharField(
        label=("Kode RS"), required=True, max_length=30)
    kode_ruangan = forms.CharField(
        label=("Kode Ruangan"), required=True, max_length=30)

    def __init__(self, *args, **kwargs):
        super(Update_Reservasi_Hotel, self).__init__(*args, **kwargs)
        self.fields['nik'].widget.attrs['readonly'] = True
        self.fields['nik'].widget.attrs['class'] = 'disabled'
        self.fields['tanggal_masuk'].widget.attrs['readonly'] = True
        self.fields['tanggal_masuk'].widget.attrs['class'] = 'disabled'
        self.fields['kode_hotel'].widget.attrs['readonly'] = True
        self.fields['kode_hotel'].widget.attrs['class'] = 'disabled'
        self.fields['kode_ruangan'].widget.attrs['readonly'] = True
        self.fields['kode_ruangan'].widget.attrs['class'] = 'disabled'

Reservasi_Hotel/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from django.db import connection
from datetime import datetime

def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        if 'is_login' not in request.session:
            return redirect('login:login_or_register')
        else:
            return function(request, *args, **kwargs)
    return wrapper

@ user_login_required
def create_reservasi_hotel(request):
    if request.session['peran'] != 'Admin Satgas' and request.session['peran'] != 'Pengguna Publik':
        return redirect('login:login_or_register')
    form = Create_Reservasi_Hotel(request.session['username'], request.session['peran'])
    if request.method == "POST":
        kode_pasien = request.POST['nik']
        tgl_masuk = request.POST['tanggal_masuk']
        tgl_keluar = request.POST['tanggal_keluar']
        kode_hotel = request.POST['kode_hotel']
        kode_room = request.POST['kode_ruangan']

        data_baru = [kode_pasien, tgl_masuk, tgl_keluar, kode_hotel, kode_room]
        print(data_baru)
        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO SIRUCO.RESERVASI_HOTEL VALUES (%s, %s, %s, %s, %s)', data_baru)
        return redirect('Reservasi_Hotel:read')
    return render(request, 'Reservasi_Hotel/create_reservasi_hotel.html', {'form': form})

def change_ruangan_hotel(request):
    print(request.GET.get('kode_hotel'))
    kode_hotel = request.GET.get('kode_hotel')
    print(kode_hotel)
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT KODEROOM FROM SIRUCO.HOTEL_ROOM WHERE KODEHOTEL = %s", [kode_hotel])
        data = cursor.fetchall()
    list_ruangan = []
    for i in data:
        list_ruangan.append(i[0])

    return JsonResponse({'ruangan': list_ruangan})

@user_login_required
def read_reservasi_hotel(request):
    if request.session['peran'] != 'Pengguna Publik' and request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    if request.session['peran'] == 'Pengguna Publik':
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT * FROM SIRUCO.RESERVASI_HOTEL WHERE KODEPASIEN IN (SELECT NIK FROM SIRUCO.PASIEN WHERE idpendaftar= %s)", [request.session['username']])
            data = dictfetchall(cursor)
        context = {'apt': data, 'date': datetime.today().strftime('%Y-%m-%d')}
    else:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM SIRUCO.RESERVASI_HOTEL")
            data = dictfetchall(cursor)
        context = {'apt': data, 'date': datetime.today().strftime('%Y-%m-%d')}
    return render(request, 'Reservasi_Hotel/read_reservasi_hotel.html', context)

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

@user_login_required
def update_reservasi_hotel(request):
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    form = Update_Reservasi_Hotel()
    if request.method == 'GET':
        print(request.GET.get('kodepasien'), request.GET.get('tglmasuk'))
        if request.GET.get('kodepasien') is not None and request.GET.get('tglmasuk') is not None:
            print(23232)
            kodepasien = request.GET.get('kodepasien')
            tglmasuk = request.GET.get('tglmasuk')
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT * FROM SIRUCO.RESERVASI_HOTEL where kodepasien = %s AND tglmasuk = %s LIMIT 1;', [kodepasien, tglmasuk])
                data = dictfetchall(cursor)
            data_pasien = {}
            data_pasien['nik'] = data[0]['kodepasien']
            data_pasien['tanggal_masuk'] = data[0]['tglmasuk']
            data_pasien['tanggal_keluar'] = data[0]['tglkeluar']
            data_pasien['kode_hotel'] = data[0]['kodehotel']
            data_pasien['kode_ruangan'] = data[0]['koderoom']
            form = Update_Reservasi_Hotel(initial=data_pasien)
    else:
        kodepasien = request.POST['nik']
        tglkeluar = request.POST['tanggal_keluar']
        tglmasuk = request.POST['tanggal_masuk']
        data_to_update = [tglkeluar, kodepasien, tglmasuk]
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE SIRUCO.RESERVASI_HOTEL SET tglkeluar = %s WHERE KODEPASIEN = %s and TGLMASUK = %s", data_to_update)
        return redirect('Reservasi_Hotel:read')
    return render(request, 'Reservasi_Hotel/update_reservasi_hotel.html', {'form': form})


@user_login_required
def delete_reservasi_hotel(request):
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    if request.method == 'GET':
        if request.GET.get('kodepasien') is not None and request.GET.get('tglmasuk') is not None:
            kodepasien = request.GET.get('kodepasien')
            tglmasuk = request.GET.get('tglmasuk')
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT idtransaksibooking FROM SIRUCO.TRANSAKSI_BOOKING WHERE kodepasien = %s AND tglmasuk = %s', [kodepasien, tglmasuk])
                data = dictfetchall(cursor)
                idtransaksi = data[0]['idtransaksibooking']
                cursor.execute(
                    'DELETE FROM SIRUCO.RESERVASI_HOTEL WHERE kodepasien = %s AND tglmasuk = %s', [kodepasien, tglmasuk])
                cursor.execute(
                    'DELETE FROM SIRUCO.TRANSAKSI_HOTEL WHERE idtransaksi = %s', [idtransaksi])
    return HttpResponseRedirect(reverse('Reservasi_Hotel:read'))

Reservasi_Hotel/templates/Reservasi_Hotel/create_reservasi_hotel.html
{% extends "login/landing_page.html" %}

{% block content %}

<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Create Reservasi Hotel Form</h1>
        <div style="height: 20px;"></div>
        <form id="formnya" action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <label for="kode_ruangan">Kode Ruangan:</label>
            <select name="kode_ruangan" id="kode_ruangan">
            </select>
            <br>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock content %}

{% block tambahScript %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script>

    $(document).ready(function () {
        $('#formnya').on('submit', function (e) {
            const tgl_masuk = $('#tanggal_masuk').val();
            const tgl_keluar = $('#tanggal_keluar').val();
            console.log(tgl_masuk)
            console.log(tgl_keluar)
            if (tgl_masuk > tgl_keluar) {
                alert('Tanggal masuk tidak boleh lebih dari tanggal keluar!')
                e.preventDefault();
            }
        })

        $.ajax({
            type: 'GET',
            url: "{% url 'Reservasi_Hotel:change_ruangan_hotel' %}",
            data: {
                kode_hotel: $('#kode_hotel').val()
            },
            async: false,
            success: function (response) {
                response.ruangan.map((e) => {
                    $('#kode_ruangan').append(new Option(e, e))
                })
            }
        });

        $('#kode_hotel').on('change', function () {
            $('#kode_ruangan').find('option').remove()
            $.ajax({
                type: 'GET',
                url: "{% url 'Reservasi_Hotel:change_ruangan_hotel' %}",
                data: {
                    kode_hotel: $('#kode_hotel').val()
                },
                async: false,
                success: function (response) {
                    response.ruangan.map((e) => {
                        $('#kode_ruangan').append(new Option(e, e))
                    })
                }
            });

        });

    })


</script>
{% endblock tambahScript %}

Reservasi_Hotel/templates/Reservasi_Hotel/read_reservasi_hotel.html
{% extends "login/landing_page.html" %}

{% block content %}


<h1 class="text-center">Daftar Reservasi Hotel</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">NIK Pasien</th>
            <th scope="col">Tanggal Masuk</th>
            <th scope="col">Tanggal Keluar</th>
            <th scope="col">Kode Hotel</th>
            <th scope="col">Ruangan</th>

            {% if request.session.peran == 'Admin Satgas' %}
            <th scope="col"></th>
            <th scope="col"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>

        {% for ap in apt %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{ ap.kodepasien }}</td>
            <td>{{ ap.tglmasuk }} </td>
            <td>{{ ap.tglkeluar }}</td>
            <td>{{ ap.kodehotel }}</td>
            <td>{{ ap.koderoom }}</td>
            </td>

            {% if request.session.peran == 'Admin Satgas' %}
            <td>
                <form action="{% url 'Reservasi_Hotel:update' %}" method="get">
                    <input type="hidden" id="kodepasien" name="kodepasien" value="{{ ap.kodepasien }}">
                    <input type="hidden" id="tglmasuk" name="tglmasuk" value="{{ ap.tglmasuk }}">
                    <button type="submit" class="btn btn-outline-warning">Update</button>
                </form>
            </td>
            {% if ap.tglmasuk|date:'Y-m-d' > date %} <td>
                <form action="{% url 'Reservasi_Hotel:delete' %}" method="get">
                    <input type="hidden" id="kodepasien" name="kodepasien" value="{{ ap.kodepasien }}">
                    <input type="hidden" id="tglmasuk" name="tglmasuk" value="{{ ap.tglmasuk }}">
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </form>
            </td>
            {% endif %}
            </td>
            {% endif %}
        </tr>

        {% endfor %}

    </tbody>
</table>


{% endblock content %}

Reservasi_Hotel/templates/Reservasi_Hotel/update_reservasi_hotel.html
{% extends "login/landing_page.html" %}
{% block tambahStyle %}
<style>
    .disabled {
        background-color: rgba(22, 16, 16, 0.3), rgba(59, 59, 59, 0.3);
        border-color: rgba(118, 118, 118, 0.3);
    }
</style>
{% endblock tambahStyle %}
{% block content %}



<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Update Reservasi RS Form</h1>
        <div style="height: 20px;"></div>
        <form id="formCreate" action="{% url 'Reservasi_Hotel:update' %}" method="POST">
            {% csrf_token %}

            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
{% endblock content %}
{% block tambahScript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

    $(document).ready(function () {
        $('#formCreate').on('submit', function (e) {
            const tgl_masuk = $('#tanggal_masuk').val();
            const tgl_keluar = $('#tanggal_keluar').val();
            console.log(tgl_masuk)
            console.log(tgl_keluar)
            if (tgl_masuk > tgl_keluar) {
                alert('Tanggal masuk tidak boleh lebih dari tanggal keluar!')
                e.preventDefault();
            }
        })
    })


</script>
{% endblock tambahScript %}