hotel/urls.py
from django.urls import path
from .views import create_hotel, read_hotel, update_hotel

app_name = 'hotel'

urlpatterns = [
    path('create/', create_hotel, name='create'),
    path('read/', read_hotel, name='read'),
    path('update/', update_hotel, name='update'),
]

login/urls.py
from django.urls import path

from .views import profile, login, logout_view, login_or_register, register, register_admin_sistem, register_pengguna_publik, register_dokter, register_admin_satgas

app_name = 'login'

urlpatterns = [
    path('', login_or_register, name='login_or_register'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('register/adminsistem', register_admin_sistem,
         name='register_admin_sistem'),
    path('register/adminsatgas', register_admin_satgas,
         name='register_admin_satgas'),
    path('register/dokter', register_dokter, name='register_dokter'),
    path('register/penggunapublik', register_pengguna_publik,
         name='register_pengguna_publik'),



    path('profile/', profile, name='profile')


]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('jadwal-faskes/', include('jadwal_faskes.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('reservasiRS/', include('reservasiRS.urls')),
    path('transaksiRS/', include('transaksirs.urls')),
    path('jadwaldokter/',include('jadwaldokter.urls')),

    path('hotel/', include('hotel.urls')),
    path('paketmakan/', include('paketmakan.urls')),
    path('ruangan_hotel/', include('ruangan_hotel.urls')),
    path('reservasi_hotel/', include('Reservasi_Hotel.urls')),
    path('transaksi_hotel/', include('transaksi_hotel.urls')),
    path('transaksi_booking/', include('transaksi_booking.urls')),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.db import connection


class LoginForm(forms.Form):
    username = forms.CharField(
        label=("Username"), required=True, max_length=50)
    password = forms.CharField(
        label=("Password"), widget=forms.PasswordInput, required=True, max_length=128)


class RegisterAdminSistemForm(forms.Form):
    email = forms.CharField(label=("Email"), required=True, max_length=50)
    password = forms.CharField(
        label=("Password"), widget=forms.PasswordInput, required=True, max_length=128)


class RegisterPenggunaPublikForm(forms.Form):
    email = forms.CharField(label=("Email"), required=True, max_length=50)
    password = forms.CharField(
        label=("Password"), widget=forms.PasswordInput, required=True, max_length=128)
    nama_lengkap = forms.CharField(
        label=("Nama Lengkap"), required=True, max_length=50)
    NIK = forms.CharField(label=("NIK"), required=True, max_length=20)
    no_hp = forms.CharField(label=("No HP"), required=True, max_length=12)


class RegisterDokterForm(forms.Form):
    email = forms.CharField(label=("Email"), required=True, max_length=50)
    password = forms.CharField(
        label=("Password"), widget=forms.PasswordInput, required=True, max_length=128)
    nama_lengkap = forms.CharField(
        label=("Nama Lengkap"), required=True, max_length=50)
    no_str = forms.CharField(label=("No STR"), required=True, max_length=20)
    no_hp = forms.CharField(label=("No HP"), required=True, max_length=20)
    gelar_depan = forms.CharField(
        label=("Gelar Depan"), required=True, max_length=20)
    gelar_belakang = forms.CharField(
        label=("Gelar Belakang"), required=True, max_length=20)


class RegisterAdminSatgasForm(forms.Form):
    email = forms.CharField(label=("Email"), required=True, max_length=50)
    password = forms.CharField(
        label=("Password"), widget=forms.PasswordInput, required=True, max_length=128)
    kode_faskes_list = []
    kode_faskes = forms.ChoiceField(choices=kode_faskes_list, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT KODE, KODE FROM SIRUCO.FASKES")
            self.fields['kode_faskes'].choices = cursor.fetchall()


class UpdateProfileForm(forms.Form):
    username = forms.CharField(
        label=("Username"), required=True, max_length=30)
    password = forms.CharField(label=("Password"), widget=forms.PasswordInput(render_value=True),
                               required=True, max_length=30)
    peran = forms.CharField(
        label=("Peran"), required=True, max_length=30)

    def __init__(self, *args, **kwargs):
        super(UpdateProfileForm, self).__init__(*args, **kwargs)
        self.fields['peran'].disabled = True
        self.fields['password'].disabled = True

login/views.py
from django.shortcuts import render, redirect
from django.forms import formset_factory
from django.db import connection

from .forms import LoginForm, RegisterDokterForm, RegisterAdminSatgasForm, RegisterAdminSistemForm, RegisterPenggunaPublikForm, UpdateProfileForm
# Create your views here.


def login(request):
    # Belum Login
    if 'is_login' not in request.session:
        form = LoginForm()
        if request.method == "POST":
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                # check di tabel user
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"SELECT * FROM SIRUCO.AKUN_PENGGUNA WHERE username='{username}' AND password='{password}'")
                    data = cursor.fetchone()

                print(data)
                # User Ketemu
                if data:
                    # cari tipe user
                    peran = None
                    request.session['username'] = data[0]
                    request.session['peran'] = data[2]
                    request.session['is_login'] = True

                    return redirect('login:login_or_register')
                # User Tidak Ketemu
                else:
                    return render(request, 'login/login.html', {'form': form, 'message': 'User tidak ditemukan!'})
        # Method Get (Halaman Login)
        return render(request, 'login/login.html', {'form': form})
    # Sudah Login
    else:
        return redirect('login:login_or_register')


def login_or_register(request):
    # Belum Login
    if 'is_login' not in request.session:
        return render(request, 'login/login_or_register.html')
    else:
        username = request.session['username']
        peran = request.session['peran']
        context = {'username': username, 'peran': peran}
        return render(request, 'login/landing_page.html', context)


def register(request):
    if 'is_login' in request.session:
        return redirect('login:login_or_register')
    return render(request, 'login/register.html')


def register_admin_sistem(request):
    if 'is_login' in request.session:
        return redirect('login:login_or_register')
    # Belum Login
    form = RegisterAdminSistemForm()
    if request.method == "POST":
        form = RegisterAdminSistemForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            new_data = [username, password, 'Admin Sistem']
            # lolos trigger
            try:
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"INSERT INTO SIRUCO.AKUN_PENGGUNA VALUES (%s, %s, %s)", new_data)
                    cursor.execute(
                        "INSERT INTO SIRUCO.ADMIN VALUES (%s)", [username])
                request.session['username'] = username
                request.session['peran'] = 'Admin Sistem'
                request.session['is_login'] = True
                return redirect('login:login_or_register')
            # galolos trigger
            except:
                print('galolos trigger')
                return render(request, 'login/register_admin_sistem.html', {'form': form, 'message': 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka!'})
    # Method Get (Halaman Login)
    return render(request, 'login/register_admin_sistem.html', {'form': form})


def register_pengguna_publik(request):
    if 'is_login' in request.session:
        return redirect('login:login_or_register')
    # Belum Login
    form = RegisterPenggunaPublikForm()
    if request.method == "POST":
        form = RegisterPenggunaPublikForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            nama = form.cleaned_data['nama_lengkap']
            nik = form.cleaned_data['NIK']
            no_hp = form.cleaned_data['no_hp']
            new_data = [username, nik, nama, 'AKTIF', 'Pengguna Publik', no_hp]
            # lolos trigger
            try:
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"INSERT INTO SIRUCO.AKUN_PENGGUNA VALUES (%s, %s, %s)", [username, password, 'Pengguna Publik'])
                    cursor.execute(
                        f"INSERT INTO SIRUCO.PENGGUNA_PUBLIK VALUES (%s, %s, %s, %s, %s, %s)", new_data)
                request.session['username'] = username
                request.session['peran'] = 'Pengguna Publik'
                request.session['is_login'] = True
                return redirect('login:login_or_register')

            # galolos trigger
            except:
                print('galolos trigger')
                return render(request, 'login/register_pengguna_publik.html', {'form': form, 'message': 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka!'})
    # Method Get (Halaman Login)
    return render(request, 'login/register_pengguna_publik.html', {'form': form})


def register_dokter(request):
    if 'is_login' in request.session:
        return redirect('login:login_or_register')
    form = RegisterDokterForm()
    if request.method == "POST":
        form = RegisterDokterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            nama = form.cleaned_data['nama_lengkap']
            no_str = form.cleaned_data['no_str']
            gelar_depan = form.cleaned_data['gelar_depan']
            gelar_belakang = form.cleaned_data['gelar_belakang']
            no_hp = form.cleaned_data['no_hp']
            new_data = [username, no_str, nama,
                        no_hp, gelar_depan, gelar_belakang]
            # lolos trigger
            try:
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"INSERT INTO SIRUCO.AKUN_PENGGUNA VALUES (%s, %s, %s)", [username, password, 'Dokter'])
                    cursor.execute(
                        "INSERT INTO SIRUCO.ADMIN VALUES (%s)", [username])
                    cursor.execute(
                        f"INSERT INTO SIRUCO.DOKTER VALUES (%s, %s, %s, %s, %s, %s)", new_data)
                request.session['username'] = username
                request.session['peran'] = 'Dokter'
                request.session['is_login'] = True
                return redirect('login:login_or_register')

            # galolos trigger
            except:
                print('galolos trigger')
                return render(request, 'login/register_dokter.html', {'form': form, 'message': 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka!'})
    # Method Get (Halaman Login)
    return render(request, 'login/register_dokter.html', {'form': form})


def register_admin_satgas(request):
    if 'is_login' in request.session:
        return redirect('login:login_or_register')
    # Belum login
    form = RegisterAdminSatgasForm()
    if request.method == "POST":
        form = RegisterAdminSatgasForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            new_data = [username, password, 'Admin Satgas']
            kode_faskes = form.cleaned_data['kode_faskes']
            # lolos trigger
            try:
                with connection.cursor() as cursor:
                    cursor.execute(
                        f"INSERT INTO SIRUCO.AKUN_PENGGUNA VALUES (%s, %s, %s)", new_data)
                    cursor.execute(
                        "INSERT INTO SIRUCO.ADMIN VALUES (%s)", [username])
                    cursor.execute(
                        "INSERT INTO SIRUCO.ADMIN_SATGAS VALUES (%s, %s)", [username, kode_faskes])

                request.session['username'] = username
                request.session['peran'] = 'Admin Satgas'
                request.session['is_login'] = True
                return redirect('login:login_or_register')
            # galolos trigger
            except:
                print('galolos trigger')
                return render(request, 'login/register_admin_satgas.html', {'form': form, 'message': 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka!'})
    # Method Get (Halaman Login)
    return render(request, 'login/register_admin_satgas.html', {'form': form})


def logout_view(request):
    del request.session['username']
    del request.session['peran']
    del request.session['is_login']
    return redirect('login:login')


def profile(request):
    if 'is_login' not in request.session:
        return redirect('login:login_or_register')
    if request.method == 'GET':
        username = request.session['username']
        with connection.cursor() as cursor:
            cursor.execute(
                'SELECT * FROM SIRUCO.AKUN_PENGGUNA where username=%s;', [username])
            data = dictfetchall(cursor)
        data_profil = {}
        print(data[0])
        data_profil['username'] = data[0]['username']
        data_profil['password'] = data[0]['password']
        data_profil['peran'] = data[0]['peran']
        form = UpdateProfileForm(initial=data_profil)
    else:
        # print('WOIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII')
        # print(request.POST)
        username = request.POST['username']
        with connection.cursor() as cursor:
            cursor.execute(
                    "select username from SIRUCO.AKUN_PENGGUNA")
            data = dictfetchall(cursor)

login/templates/login/login.html
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
</head>

<header>
    <div>
        <a href="/">
            <svg class="bi bi-arrow-left-short" width="6em" height="5em" viewBox="0 0 16 16" fill="black"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M7.854 4.646a.5.5 0 010 .708L5.207 8l2.647 2.646a.5.5 0 01-.708.708l-3-3a.5.5 0 010-.708l3-3a.5.5 0 01.708 0z"
                    clip-rule="evenodd" />
                <path fill-rule="evenodd" d="M4.5 8a.5.5 0 01.5-.5h6.5a.5.5 0 010 1H5a.5.5 0 01-.5-.5z"
                    clip-rule="evenodd" />
            </svg>
        </a>
    </div>
</header>
<div class="centered">

    <h1 style="text-align: center;">Login Form</h1>
    <div style="height: 20px;"></div>
    {{message}}
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login">
        <div class="form-group row">
            <div>
                <p>Belum punya akun? daftar <a href="/register">disini.</a></p>
            </div>
        </div>
    </form>
</div>



</html>

login/templates/login/login_or_register.html
<!DOCTYPE html>
<html>

<head>
    <title>Login or Register</title>
</head>

<body>
    <h1>
        Mau Login apa Register?
    </h1>
    <div>
        <form>
            <button>
                <a href="{% url 'login:login' %}">Login</a>
            </button>
            <button>
                <a href="{% url 'login:register' %}">Register</a>
            </button>
        </form>
    </div>
</body>

</html>

login/templates/login/profile.html
{% extends "login/landing_page.html" %}


{% block content %}


{{message}}



<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Update Profile</h1>
        <div style="height: 20px;"></div>
        <form action="{% url 'login:profile' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>






{% endblock content %}

login/templates/login/register.html
<!DOCTYPE html>
<html>

<head>
    <title>Register</title>
</head>

<body>
    <h1>
        Mau register sebagai apa?
    </h1>
    <div class=register>
        <form id=register>
            <button>
                <a href="{% url 'login:register_admin_sistem' %}">ADMIN SISTEM</a>
            </button>
            <button>
                <a href="{% url 'login:register_pengguna_publik' %}">PENGGUNA PUBLIK</a>
            </button>
            <button>
                <a href="{% url 'login:register_dokter' %}">DOKTER</a>
            </button>
            <button>
                <a href="{% url 'login:register_admin_satgas' %}">ADMIN SATGAS</a>
            </button>
        </form>
    </div>
</body>

</html>

login/templates/login/register_admin_satgas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="centered">

        <h1 style="text-align: center;">Admin Satgas Form</h1>
        <div style="height: 20px;"></div>
        {{message}}
        <form style="justify-content: center; display:flex; align-items:center; flex-direction:column" action=""
            method="POST">
            {% csrf_token %}

            {{form.as_p}}

            <input type="submit" value="Login">
            <div class="form-group row">
            </div>
        </form>
    </div>
</body>

</html>

login/templates/login/register_admin_sistem.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="centered">

        <h1 style="text-align: center;">Admin Sistem Form</h1>
        <div style="height: 20px;"></div>
        {{message}}
        <form style="justify-content: center; display:flex; align-items:center; flex-direction:column" action=""
            method="POST">
            {% csrf_token %}
            {{form.as_p}}
            {{form.kode_faskes}}
            <input type="submit" value="Login">
            <div class="form-group row">
            </div>
        </form>
    </div>
</body>

</html>

login/templates/login/register_dokter.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="centered">

        <h1 style="text-align: center;">Dokter Form</h1>
        <div style="height: 20px;"></div>
        {{message}}
        <form style="justify-content: center; display:flex; align-items:center; flex-direction:column" action=""
            method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Login">
            <div class="form-group row">
            </div>
        </form>
    </div>
</body>

</html>

login/templates/login/register_pengguna_publik.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="centered">

        <h1 style="text-align: center;">Pengguna Publik Form</h1>
        <div style="height: 20px;"></div>
        {{message}}
        <form style="justify-content: center; display:flex; align-items:center; flex-direction:column" action=""
            method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Login">
            <div class="form-group row">
            </div>
        </form>
    </div>
</body>

</html>