faskes/urls.py
from django.urls import path

# from .views import login, logout_view, login_or_register, register, register_admin_sistem, register_pengguna_publik, register_dokter, register_admin_satgas
from .views import delete_faskes, read_faskes, detail_faskes, update_faskes, create_faskes
app_name = 'faskes'

urlpatterns = [
    path('create/', create_faskes, name='create'),
    path('read/', read_faskes, name='read'),
    path('details/', detail_faskes, name='details'),
    path('update/', update_faskes, name='update'),
    path('delete/', delete_faskes, name='delete'),
]

hotel/urls.py
from django.urls import path
from .views import create_hotel, read_hotel, update_hotel

app_name = 'hotel'

urlpatterns = [
    path('create/', create_hotel, name='create'),
    path('read/', read_hotel, name='read'),
    path('update/', update_hotel, name='update'),
]

siruco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('jadwal-faskes/', include('jadwal_faskes.urls')),
    path('rumahsakit/', include('rumahsakit.urls')),
    path('reservasiRS/', include('reservasiRS.urls')),
    path('transaksiRS/', include('transaksirs.urls')),
    path('jadwaldokter/',include('jadwaldokter.urls')),

    path('hotel/', include('hotel.urls')),
    path('paketmakan/', include('paketmakan.urls')),
    path('ruangan_hotel/', include('ruangan_hotel.urls')),
    path('reservasi_hotel/', include('Reservasi_Hotel.urls')),
    path('transaksi_hotel/', include('transaksi_hotel.urls')),
    path('transaksi_booking/', include('transaksi_booking.urls')),
]

faskes/models.py
from django.db import models

# Create your models here.

faskes/forms.py
from django import forms
from django.db import connection


class CreateFaskesForm(forms.Form):
    tipe_faskes_list = [('Rumah Sakit', 'Rumah Sakit'),
                        ('Puskesmas', 'Puskesmas'), ('Klinik', 'Klinik')]
    status_faskes_list = [('Swasta', 'Swasta'), ('Pemerintah', 'Pemerintah')]
    kode = forms.CharField(label=("Kode Faskes"), required=True, max_length=3)
    tipe = forms.ChoiceField(
        label=('Tipe'), required=True, choices=tipe_faskes_list)
    nama = forms.CharField(label=("Nama Faskes"), required=True, max_length=50)
    status = forms.ChoiceField(
        label=('Status Kepemilikan'), required=True, choices=status_faskes_list)
    jalan = forms.CharField(label=("Jalan"), required=True, max_length=30)
    kelurahan = forms.CharField(
        label=("Kelurahan"), required=True, max_length=30)
    kecamatan = forms.CharField(
        label=("Kecamatan"), required=True, max_length=30)
    kabkot = forms.CharField(label=("Kabpuaten/Kota"),
                             required=True, max_length=30)
    provinsi = forms.CharField(
        label=("Provinsi"), required=True, max_length=30)

    def __init__(self, *args, **kwargs):
        super(CreateFaskesForm, self).__init__(*args, **kwargs)
        self.fields['kode'].widget.attrs['readonly'] = True
        self.fields['kode'].widget.attrs['class'] = 'disabled'
        kode_baru = ''
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT KODE FROM SIRUCO.FASKES ORDER BY KODE DESC LIMIT 1")
            # print(cursor.fetchall()[0][0][1:])
            kode_baru = 'F' + self.manip(cursor.fetchall()[0][0][1:])
        self.fields['kode'].initial = kode_baru

    def manip(self, kode):
        res = ''
        print(kode)
        if kode[-1] == '9':
            res += str(int(kode[0])+1) + '0'
        else:
            print(kode, 'OI')
            res += (kode[0] + str(int(kode[-1]) + 1))
        return res


class UpdateFaskesForm(forms.Form):
    tipe_faskes_list = [('Rumah Sakit', 'Rumah Sakit'),
                        ('Puskesmas', 'Puskesmas'), ('Klinik', 'Klinik')]
    status_faskes_list = [('Swasta', 'Swasta'), ('Pemerintah', 'Pemerintah')]
    kode = forms.CharField(label=("Kode Faskes"), required=True, max_length=3)
    tipe = forms.ChoiceField(
        label=('Tipe'), required=True, choices=tipe_faskes_list)
    nama = forms.CharField(label=("Nama Faskes"), required=True, max_length=50)
    status = forms.ChoiceField(
        label=('Status Kepemilikan'), required=True, choices=status_faskes_list)
    jalan = forms.CharField(label=("Jalan"), required=True, max_length=30)
    kelurahan = forms.CharField(
        label=("Kelurahan"), required=True, max_length=30)
    kecamatan = forms.CharField(
        label=("Kecamatan"), required=True, max_length=30)
    kabkot = forms.CharField(label=("Kabpuaten/Kota"),
                             required=True, max_length=30)
    provinsi = forms.CharField(
        label=("Provinsi"), required=True, max_length=30)

    def __init__(self, *args, **kwargs):
        super(UpdateFaskesForm, self).__init__(*args, **kwargs)
        self.fields['kode'].widget.attrs['readonly'] = True
        self.fields['kode'].widget.attrs['class'] = 'disabled'

faskes/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from django.db import connection

#
# Create your views here.


def user_login_required(function):
    def wrapper(request, *args, **kwargs):
        if 'is_login' not in request.session:
            return redirect('login:login_or_register')
        else:
            return function(request, *args, **kwargs)
    return wrapper


@user_login_required
def create_faskes(request):
    # Jika bukan pengguna publik
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    print(request.session['username'])
    form = CreateFaskesForm()
    if request.method == "POST":
        kode = request.POST['kode']
        tipe = request.POST['tipe']
        nama = request.POST['nama']
        status = request.POST['status']
        jalan = request.POST['jalan']
        kelurahan = request.POST['kelurahan']
        kecamatan = request.POST['kecamatan']
        kabkot = request.POST['kabkot']
        provinsi = request.POST['provinsi']
        data_baru = [kode, tipe, nama, status, jalan,
                     kelurahan, kecamatan, kabkot, provinsi]
        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO SIRUCO.FASKES VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)', data_baru)
        return redirect('faskes:read')
    return render(request, 'faskes/createFaskes.html', {'form': form, 'peran': request.session['peran']})


@user_login_required
def update_faskes(request):
    # Jika bukan pengguna publik
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    if request.method == 'GET':
        if request.GET.get('kode') is not None:
            kode = request.GET.get('kode')
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT * FROM SIRUCO.FASKES where kode=%s LIMIT 1;', [kode])
                data = dictfetchall(cursor)
            data_faskes = {}
            data_faskes['kode'] = data[0]['kode']
            data_faskes['tipe'] = data[0]['tipe']
            data_faskes['nama'] = data[0]['nama']
            data_faskes['status'] = data[0]['statusmilik']
            data_faskes['jalan'] = data[0]['jalan']
            data_faskes['kelurahan'] = data[0]['kelurahan']
            data_faskes['kecamatan'] = data[0]['kecamatan']
            data_faskes['kabkot'] = data[0]['kabkot']
            data_faskes['provinsi'] = data[0]['prov']
            form = UpdateFaskesForm(initial=data_faskes)
    else:
        # print('WOIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII')
        # print(request.POST)
        kode = request.POST['kode']
        tipe = request.POST['tipe']
        nama = request.POST['nama']
        status = request.POST['status']
        jalan = request.POST['jalan']
        kelurahan = request.POST['kelurahan']
        kecamatan = request.POST['kecamatan']
        kabkot = request.POST['kabkot']
        provinsi = request.POST['provinsi']
        data_baru = [tipe, nama, status, jalan,
                     kelurahan, kecamatan, kabkot, provinsi, kode]
        with connection.cursor() as cursor:
            cursor.execute(
                "UPDATE SIRUCO.FASKES SET tipe = %s, nama = %s,statusmilik = %s,jalan = %s,kelurahan = %s,kecamatan = %s,kabkot = %s,prov = %s WHERE KODE = %s", data_baru)
        return redirect('faskes:read')
    return render(request, 'faskes/updateFaskes.html', {'form': form})


@user_login_required
def delete_faskes(request):
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    if request.method == 'GET':
        if request.GET.get('kode') is not None:
            kode_faskes = request.GET.get('kode')
            with connection.cursor() as cursor:
                cursor.execute(
                    'DELETE FROM SIRUCO.FASKES WHERE kode = %s', [kode_faskes])
    return HttpResponseRedirect(reverse('faskes:read'))


@user_login_required
def read_faskes(request):
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM SIRUCO.FASKES")
        seluruh = dictfetchall(cursor)
    context = {'apt': seluruh}
    return render(request, 'faskes/readFaskes.html', context)


@user_login_required
def detail_faskes(request):
    print(request.session['peran'], 'OI')
    if request.session['peran'] != 'Admin Satgas':
        return redirect('login:login_or_register')
    if request.method == 'GET':
        if request.GET.get('kode') is not None:
            kode_faskes = request.GET.get('kode')
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT * FROM SIRUCO.FASKES where kode=%s LIMIT 1;', [kode_faskes])
                data = dictfetchall(cursor)

    return render(request, 'faskes/detailsFaskes.html', data[0])


def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

faskes/templates/faskes/createFaskes.html
{% extends "login/landing_page.html" %}
{% block tambahStyle %}
<style>
    .disabled {
        background-color: rgba(239, 239, 239, 0.3), rgba(59, 59, 59, 0.3);
        border-color: rgba(118, 118, 118, 0.3);
    }
</style>
{% endblock tambahStyle %}
{% block content %}



<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Create Faskes Form</h1>
        <div style="height: 20px;"></div>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock content %}

faskes/templates/faskes/detailsFaskes.html
{% extends "login/landing_page.html" %}


{% block content %}

<h1 class="text-center">Detail Faskes</h1>
<table class="table">
    <tbody>
        <tr>
            <th scope="row">Kode Faskes</th>
            <td>{{kode}}</td>

        </tr>
        <tr>
            <th scope="row">Tipe</th>
            <td>{{tipe}}</td>

        </tr>
        <tr>
            <th scope="row">Nama Faskes</th>
            <td>{{nama}}</td>
        </tr>
        <tr>
            <th scope="row">Status Kepemilikan</th>
            <td>{{statusmilik}}</td>
        </tr>
        <tr>
            <th scope="row">Jalan </th>
            <td>{{jalan}}</td>
        </tr>
        <tr>
            <th scope="row">Kelurahan </th>
            <td>{{kelurahan}}</td>
        </tr>
        <tr>
            <th scope="row">Kecamatan </th>
            <td>{{kecamatan}}</td>
        </tr>
        <tr>
            <th scope="row">Kabupaten/Kota </th>
            <td>{{kabkot}}</td>
        </tr>
        <tr>
            <th scope="row">Provinsi </th>
            <td>{{prov}}</td>
        </tr>

    </tbody>
</table>
<div style="display: flex;justify-content:center;align-items:center">
    <button class="btn btn-warning"><a href="{% url 'faskes:read'%}">Kembali</a></button>
</div>
{% endblock content %}

faskes/templates/faskes/readFaskes.html
{% extends "login/landing_page.html" %}

{% block content %}


<h1 class="text-center">Daftar faskes</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Kode Faskes</th>
            <th scope="col">Tipe</th>
            <th scope="col">Nama Faskes</th>
            {% if request.session.peran == 'Admin Satgas' %}
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>

        {% for ap in apt %}
        <tr>

            <td>{{ ap.kode }}</td>
            <td>{{ ap.tipe }}</td>
            <td>{{ ap.nama }}</td>
            {% if request.session.peran == 'Admin Satgas' %}
            <td>
                <form action="{% url 'faskes:update' %}" method="get">
                    <input type="hidden" id="kode" name="kode" value="{{ ap.kode }}">
                    <button type="submit" class="btn btn-outline-warning">Update</button>
                </form>
            </td>
            <td>

                <form action="{% url 'faskes:delete' %}" method="get">
                    <input type="hidden" id="kode" name="kode" value="{{ ap.kode }}">
                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                </form>
            </td>
            <td>
                <form action="{% url 'faskes:details' %}" method="get">
                    <input type="hidden" id="kode" name="kode" value="{{ ap.kode }}">
                    <button type="submit" class="btn btn-outline-primary">Detail</button>
                </form>
            </td>
            </td>
            {% endif %}
        </tr>

        {% endfor %}

    </tbody>
</table>


{% endblock content %}

faskes/templates/faskes/updateFaskes.html
{% extends "login/landing_page.html" %}

{% block tambahStyle %}
<style>
    .disabled {
        background-color: rgba(239, 239, 239, 0.3), rgba(59, 59, 59, 0.3);
        border-color: rgba(118, 118, 118, 0.3);
    }
</style>
{% endblock tambahStyle %}
{% block content %}
<div style="display: flex; justify-content:center; align-items:center; flex-direction:column">
    <div class="centered">
        <h1 style="text-align: center;">Update Faskes</h1>
        <div style="height: 20px;"></div>
        <form action="{% url 'faskes:update' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>




{% endblock content %}